server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://67.209.187.223:3306/dbbook?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: admin
    password: admin
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    database: MYSQL
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
#  datasource:
#    platform: h2
#    schema: classpath:schema.sql
#    data: classpath:data.sql
  application:
    name: provider-user


logging:
  path: logs/
  file: myLog.log
  level:
    root: info
eureka:
  client:
    serviceUrl:
      defaultZone: http://zhoujy:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
