server:
  port: 8010
spring:
  application:
    name: consumer-movie
eureka:
  client:
    serviceUrl:
      defaultZone: http://zhoujy:123456@localhost:8761/eureka/
  instance:
    prefer-ip-address: true